### ISSUE TITLE
[feature request] Datev SmartUpload support

### ISSUE THREAD

**Issue by cocoonkid** [david-loe/abrechnung#16]
[feature request] Datev SmartUpload support

https://www.datev.de/web/de/mydatev/datev-cloud-anwendungen/datev-upload-online/
https://developer.datev.de/datev/platform/en/online-apis

Thanks for your consideration.

**Comment by david-loe** [comment]
Hey, thanks for your suggestion!

It looks like a simple call to `POST https://accounting-documents.api.datev.de/platform/v2/clients/{client-id}/documents`.

But as I'm not using DATEV and have no account, I wouldn't be able to test this reliably..

Maybe this changes in the future, but as for now this will not get on the roadmap.
