### ISSUE TITLE
wrong lump sum used for last day of trip to foreign country.

### ISSUE THREAD

**Issue by blattms** [david-loe/abrechnung#18]
Looks quite nice already.

I assume here that this is for Germany.
If I input a  one day or multi day trip to a foreign country, then for the last day the lump sum of the country I return to is used. It should be the value for the last foreign country visited for business purposes.

Even more complicate if there is an overnight stop over on the way back in another country. The lump sum of that country should be used for the day before the day returning and for the day returning that the one of the last country visited for business purposes.

**Comment by david-loe** [comment]
Thanks for pointing that out! You're right it says:
> Bei der Abreise vom Ausland in das Inland oder vom Inland in das Ausland ist der
entsprechende Pauschbetrag des letzten Tätigkeitsortes maßgebend.

Do you have a smart idea on how to guess the _letzter Tätigkeitsort_ without user input? 😅  
Suppose the stop on the way back has a business purpose.. How should the system know?
And I think I already need to much user input.. 🙆‍♂️

**Comment by blattms** [comment]
I have an idea. You have a country when a business travel is proposed. Just use that one for the last day when you travel back.

If that country is editable then users can adjust for complicated cases.

**Comment by david-loe** [comment]
Hmm.. Doesn't this only cover travels with just one country where business has happend?

But maybe this can be the default case, and if the travel ends with multiple country stops the user is prompted to put in the country where the last business happend

**Comment by blattms** [comment]
yep that is true. That is why user would need to be able to change the country in the application later.
