### ISSUE TITLE
Cannot input travel or stages from the past.

### ISSUE THREAD

**Issue by blattms** [david-loe/abrechnung#19]
It is only allowed to input today and future days for dates when doing travel applications or adding travel stages

This might be a bit inconvenient.

**Comment by david-loe** [comment]
A setting for allowing travel application in the past might be a enhancement worth to think about, but ideally not needed.

For stages in a travel there is a setting called `toleranceStageDatesToApprovedTravelDates` which defines the boundaries according to the approved dates, so if you wait a few days after approval also dates in the past are possible to enter.
