### ISSUE TITLE
settings/adduser requires Vorname and Nachname to be a valid email address

### ISSUE THREAD

**Issue by blattms** [david-loe/abrechnung#22]

**Comment by david-loe** [comment]
Can you explain a bit more?

What did you expect? And how is it not working as expected for you?

**Comment by blattms** [comment]
I expect it to work with normal names and not that I get an error message for my normal name and surname.

If I input them like this:

![image](https://github.com/david-loe/abrechnung/assets/1944640/77be0159-bcf8-4a37-9626-c81c37c73f99)

then when I click "Benutzer hinzufügen" I get "Please enter a valid email address" for Vorname. If I delete that the error appears for Nachname.

To me this is a bug.

**Comment by david-loe** [comment]
Oh Yes, it is a bug 😅 I'll fix it

**Comment by blattms** [comment]
Many thanks for all the fixes.
If I find time I will try it some more.
