### ISSUE TITLE
Error after create  "Auslagen" an unable to login

### ISSUE THREAD

**Issue by meik1337** [david-loe/abrechnung#36]
After testing a test abrechnung.
We receive an error 

backend-1        | node:internal/process/promises:289
backend-1        |             triggerUncaughtException(err, true /* fromPromise */);
backend-1        |             ^
backend-1        |
backend-1        | Error: unable to get local issuer certificate
backend-1        |     at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
backend-1        |     at TLSSocket.emit (node:events:518:28)
backend-1        |     at TLSSocket._finishInit (node:_tls_wrap:1085:8)
backend-1        |     at ssl.onhandshakedone (node:_tls_wrap:871:12) {
backend-1        |   code: 'ESOCKET',
backend-1        |   command: 'CONN'
backend-1        | }
backend-1        |
backend-1        | Node.js v20.11.0
backend-1        | [nodemon] app crashed - waiting for file changes before starting...

**Comment by david-loe** [comment]
Can you give me some instructions on how to reproduce this error? Otherwise I'm not able to assist here

**Comment by meik1337** [comment]
Simply create Travel, after that i want to check the request. we use microsoft ad.

**Comment by david-loe** [comment]
With the informtaion you provided I can not reproduce this issue.
