### ISSUE TITLE
Etappe hinzufuegen oder Auslage hinzufuegen button does not work?

### ISSUE THREAD

**Issue by cocoonkid** [david-loe/abrechnung#4]
![image](https://github.com/david-loe/reisekostenabrechnung/assets/43231640/2f6cacf1-27d9-4848-9eef-204561c34280)

I have no error in the logs but in the browser network console Fileupload.vue seems to be called but nothing happens. 

EDIT: Found it:

![image](https://github.com/david-loe/reisekostenabrechnung/assets/43231640/f80d7c13-09ef-4eed-9124-3e3574610ee7)

**Comment by david-loe** [comment]
Hi, thanks for telling about this issue!

Could you give me more context? I'm struggeling to reproduce this issue.

Version of 'reisekostenabrechnung':
Browser and it's version:
Steps to reproduce:
