### ISSUE TITLE
Fehler beim Login / login issue

### ISSUE THREAD

**Issue by eem-mam-git** [david-loe/abrechnung#44]
Hallo,

ich bekomme eine Fehlermeldung beim Login.
![grafik](https://github.com/david-loe/abrechnung/assets/142147560/73b78efe-91dd-4a60-adbf-088378490bb6)

Installiert habe ich den container wie beschrieben. 
Was mir nicht ganz klar ist, wo wird in der .env oder docker-compose.yml der User angelegt? Oder ist der irgendwo fest geschrieben?
------------------------------------------------------------------------
English:
I get an error message when I try to log in.
 
I have installed the container as described. 
What is not quite clear to me is where the user is created in the .env or docker-compose.yml? Or is it hard-coded somewhere?

**Comment by david-loe** [comment]
Hi, die Anmeldung läuft über das LDAP was mit im `docker-compose.yml` steht.
Kannst du mal die Fehlermeldung aus deine Browserkonsole schicken?

**Comment by eem-mam-git** [comment]
Hi, der Tip mit der Konsole hat dazu geführt das ich das Problem ausfindig machen konnte. 

Fehlermeldung aus dem Browser: 
```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:8000/auth/ldapauth. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).
``` 
Durch die Fehlermeldung ist mir dann aufgefallen das mit localhost aufgelöst wird. Ich greife aber von außerhalb zu. 
habe nun die .env um die Testserver IP ergänzt. Nun geht es. 
![grafik](https://github.com/david-loe/abrechnung/assets/142147560/b6102ca3-9f33-4c4d-b5e8-69e1b2b07b0c)
