### ISSUE TITLE
how set password for new user?

### ISSUE THREAD

**Issue by eem-mam-git** [david-loe/abrechnung#48]
Hi, 

Ho its possible to set password for a new user? 

must smpt configured for this?

regards andy

**Comment by david-loe** [comment]
abrechnung uses existing identity inferstructure such as LDAP or MS-Azure OAuth.
Alternatively magic login is also implemented, this is login just with email, the user has to be created first by an admin under settings. After that he can login by giving his email address and click on the link in the email he will receive. And yes, for the SMTP has to be configured.
