### ISSUE TITLE
[feature request] show reporting, reviewing and approving person; optional option to show a field to sign the document in the created PDF

### ISSUE THREAD

**Issue by bk-lg** [david-loe/abrechnung#79]
It would be great to see in the overview of a travel view or expense view and in the resulting PDF, who approved the request and who approved the refund. 
This allows to document which person is responsible for the decision in the webapp and in the archived PDFs.

It would be a great option to have the optional setting to display an signature field for the approving person on the PDF for companies who have the problem with their local tax authority that it will only accept these documents with a signature.

**Comment by david-loe** [comment]
Displaying the approvers name is a good Idea!

I'm not sure about the signature thing, in which case is this legally required?

**Comment by bk-lg** [comment]
That is part of the problem. Since a few years this is not required anymore in germany. But a few local tax offices still don't implemented/accepted/acknowledge this change. 
So the second part of this feature request is kind of a transitional feature to allow to work with a digital tool to create and collect everything required and add the signature manually as long this is not finally resolved.

**Comment by david-loe** [comment]
Okay.. so it's just a empty field for a signature by hand?

And you would print it and sign by hand and hand in the printed document?

**Comment by bk-lg** [comment]
Hi @david-loe,
i totally missed your last question. I am really sorry. 
Yeah it would be an field to sign it by hand and then archive the paper for the tax office.

**Comment by david-loe** [comment]
@bk-lg
I have added the examiner's name to the PDF.

However, the signature field for a handwritten signature goes against my philosophy of digitalization. I hope you understand 😁

_But now you can simply sign below the printed name in the top right corner of the report._

**Comment by bk-lg** [comment]
@david-loe thank you very much and this is a good solution.
