### ISSUE TITLE
2FA ideally with FIDO U2F or minimum TOTP

### ISSUE THREAD

**Issue by Karl-Bee** [david-loe/abrechnung#83]
for security reasons 2 factor authentication would be really great.
ideally FIDO U2F (e.g. with Yubikey) or at least TOTP

and a checkbox for the admin to make 2FA mandatory for every user

**Comment by david-loe** [comment]
Out of scope, as authentication is not part of the app. It's outsourced to LDAP, Email or Azure OAuth.
You should implement 2FA in your authentication provider.
